# Generated by Django 4.2.7 on 2026-03-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='couleur',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AddField(
            model_name='domaine',
            name='icone',
            field=models.CharField(default='💼', max_length=50),
        ),
    ]
