# Generated by Django 4.2.7 on 2026-03-09 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_domaine_couleur_domaine_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='choixreponse',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple'), ('text', 'Texte libre')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='texte_libre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choixreponse',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domaine'),
        ),
        migrations.AlterField(
            model_name='reponseutilisateur',
            name='choix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.choixreponse'),
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('score_total', models.IntegerField(default=0)),
                ('domaines_recommandes', models.ManyToManyField(blank=True, to='core.domaine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section'),
        ),
    ]
