# Generated by Django 5.2.11 on 2026-04-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("section1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("recommended_field", models.CharField(max_length=100)),
                ("personality_title", models.CharField(max_length=100)),
                (
                    "confidence_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("engineering_score", models.IntegerField(default=0)),
                ("business_score", models.IntegerField(default=0)),
                ("creative_score", models.IntegerField(default=0)),
                ("social_score", models.IntegerField(default=0)),
                ("study_type", models.CharField(blank=True, max_length=100, null=True)),
                ("professional_languages", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience", models.JSONField(blank=True, default=list)),
                ("work_preferences", models.JSONField(blank=True, default=list)),
                ("personality_traits", models.JSONField(blank=True, default=list)),
                ("cv_name", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyCandidateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_score", models.IntegerField(default=0)),
                ("match_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="section1.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.JSONField(blank=True, default=list)),
                ("company_size", models.CharField(max_length=50)),
                ("location_pref", models.CharField(max_length=50)),
                ("hire_interns", models.CharField(max_length=10)),
                ("company_culture", models.JSONField(blank=True, default=list)),
                ("work_pace", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "management_style",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("core_values", models.JSONField(blank=True, default=list)),
                (
                    "work_life_balance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("skills_required", models.JSONField(blank=True, default=list)),
                (
                    "experience_level_required",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("languages_required", models.JSONField(blank=True, default=list)),
                (
                    "risk_tolerance",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("personality_required", models.JSONField(blank=True, default=list)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("benefits_offered", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CareerResult",
        ),
        migrations.AddField(
            model_name="companycandidatematch",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="section1.companyprofile",
            ),
        ),
    ]
